### ISSUE TITLE
Help me.

### ISSUE THREAD

**Issue by marcos1500** [ruckage/es-theme-nes-mini#2]
Hey Rukage , so i can't find anywhere something about the tags that i can implement or change on theme, or any tutorial about it. perhaps did you have something, excellent job that you did.

**Comment by ruckage** [comment]
Hi.  Not sure what you mean, could you clarify?

**Comment by marcos1500** [comment]
Sorry i'm a iniciate and i have no ideia the names that i need to use. i want change de visual style. but i'm not have the elements that i can change for example:

<image name="Fundo" extra="true">
		<path>./snesinfo.png</path>
		<pos>0.1 0.15</pos>	
		<size>0.25 0.7</size>
		</image>
			
		<image name="logo">
			<path>./carousel_logo_US.png</path>			
               </image>
		
		<helpsystem name="help">
			<textColor>f11c00</textColor>
			<iconColor>f11c00</iconColor>
		</helpsystem>

What is all tags that i can manipulate on xml.

**Comment by marcos1500** [comment]
as this
https://github.com/RetroPie/RetroPie-Setup/wiki/Creating-Your-Own-EmulationStation-Theme

but as you maked many modify i want know what more things i can change.

**Comment by marcos1500** [comment]
sorry for my ingles

**Comment by ruckage** [comment]
Hi.  I'm apologize but I'm not really sure I understand what you're asking.  It seems that you are asking how to make the themes but that's not something I can just tell you - you need to learn it yourself (the link you posted is a good place to start).  Is there something in particular you're trying to do?

**Comment by marcos1500** [comment]
sorry for the inconvenience, i will study more,and i will come here again.
