### ISSUE TITLE
Genesis.png missing from logos-usa and icons-usa

### ISSUE THREAD

**Issue by zcorcoran** [ruckage/es-theme-nes-mini#6]
It looks like 'genesis.png' is missing from both the icons-usa and logos-usa directories, so 
if emulationstation is configured to refer to the Megadrive as the Genesis, neither the Genesis icon nor logo will display. Genesis.png is present in both of the non-usa directories and restoring it to the -usa folders fixes the issue.

Great theme, I really love it!

**Comment by ruckage** [comment]
Thanks, already a known issue.  I hadn't considered people modifying their es_systems.cfg to support genesis but it will be fixed in the next update.

**Comment by ruckage** [comment]
Wrong theme - think you meant to post this in the SNES-mini theme. Thanks, it's already a known issue. I hadn't considered people modifying their es_systems.cfg to support genesis but it will be fixed in the next update.
