### ISSUE TITLE
Kodi on Menu

### ISSUE THREAD

**Issue by symbios24** [ruckage/es-theme-nes-mini#7]
Hello, there great theme
I have installed kodi and put it as its own system in the main menu on retropie,but the icon is not shown i only see a black/empty space, can you add support for kodi system? 

To add kodi to the menu i followed this instructions below:
i copied /etc/emulationstation/es_systems.cfg to to /opt/retropie/configs/all/emulationstation
and add the following line inside the es_systems file:
add the following codeblock anywhere after <systemList>:

<system>
<fullname>Kodi</fullname>
<name>kodi</name>
<path>~/RetroPie/roms/kodi</path>
<extension>.sh .SH</extension>
<command>bash %ROM%</command>
<platform>kodi</platform>
<theme>kodi</theme>
</system>

after that it can be shown in emulation station as a system but with your theme/s is not supported so the icon is black/empty
i also tried this with the famicom mini and snes mini theme the same result it does not show an icon only a black/empty space.

I will appreciate if you can add in all of your themes support for kodi system

Thank you

**Comment by ruckage** [comment]
Hello,

This isn't an issue as such, kodi just isn't a supported system.  It is on the to do list so will be added in the future.  You can visit the official threads at https://retropie.org.uk/forum/ to see when updates are made:

https://retropie.org.uk/forum/topic/12583/snes-mini-theme
https://retropie.org.uk/forum/topic/8391/cardboard-mini-nes-nes-mini-and-famicom-mini-themes
